language: go

os: linux

services: docker

dist: bionic

jobs:
  include:
   - stage: building x86_64 image
     arch: amd64
     script: chmod +x ./build-go.sh; ./build-go.sh
   - stage: building ppc64le image
     arch: ppc64le
     script: chmod +x ./build-go.sh; ./build-go.sh; chmod +x ./build-container.sh; ./build-container.sh
